### ISSUE TITLE
Expansion of environment variables as part of `subject-path`s does not work

### ISSUE THREAD

**Issue by sschuberth** [actions/attest-build-provenance#146]
We have a [job-global environment variable](https://github.com/oss-review-toolkit/ort/blob/2c0dc49adc3354a3dbc4c0fd1f417b73b1170b13/.github/workflows/release.yml#L19-L20) that is successfully used in other build steps, but that does not get expanded as part of [defined `subject-path`s](https://github.com/oss-review-toolkit/ort/blob/2c0dc49adc3354a3dbc4c0fd1f417b73b1170b13/.github/workflows/release.yml#L61-L65), see [this error](https://github.com/oss-review-toolkit/ort/actions/runs/9790307640/job/27031648283#step:8:52).

Is some special syntax required, or is this [another restriction](https://github.com/actions/attest-build-provenance/issues/133#issuecomment-2204292666) of `actions/glob`?

**Comment by bdehamer** [comment]
When you have a job step which invokes a command using `run` you're running an instruction within a bash shell and get all of the features of the shell like environment variable expansion:

```yaml
run: |
  gh release create $ORT_VERSION --notes-file RELEASE_NOTES.md \
      ./cli/build/distributions/ort-$ORT_VERSION.{tgz,zip}* \
      ./helper-cli/build/distributions/orth-$ORT_VERSION.{tgz,zip}*
```

When you invoke something like `actions/attest-build-provenance` with `uses` you're simply passing parameters to command and don't have the features of the bash shell available. However, you can still access environment variables using the [Actions expression syntax](https://docs.github.com/en/actions/learn-github-actions/contexts#about-contexts):

```yaml
- name: Attest Build Provenance
   uses: actions/attest-build-provenance@v1
   with:
     subject-path: |
       ./cli/build/distributions/ort-${{ env.ORT_VERSION }}.tgz
       ./cli/build/distributions/ort-${{ env.ORT_VERSION }}.zip
       ./helper-cli/build/distributions/orth-${{ env.ORT_VERSION }}.tgz
       ./helper-cli/build/distributions/orth-${{ env.ORT_VERSION }}.zip
```
