### ISSUE TITLE
Failed to get ID token: error in secret or public key callback: socket hang up

### ISSUE THREAD

**Issue by pealtrufo** [actions/attest-build-provenance#156]
Hi,

I am trying to use this action in one of my self-hosted [ARC](https://github.com/actions/actions-runner-controller) runners, but I get this error: 
`Error: Failed to get ID token: error in secret or public key callback: socket hang up`

I have been checking the action code to see if I could figure out what could be causing the issue, but I am a little bit lost. It seems to be related to the action not being able to get an ID Token from GitHub, but I struggle to see why. 

These are the permissions given to the workflow: 
```
permissions:
      id-token: write
      contents: read
      attestations: write
```
This is how I am using the action in the workflow: 
```
- name: Attest
   uses: actions/attest-build-provenance@v1
   id: attest
   with:
       subject-name: ${{ inputs.REGISTRY_SERVER }}/${{ inputs.APP_NAME }}
       subject-digest: ${{ steps.get-image-digest.outputs.imageDigest }}
       push-to-registry: true
```
I can also see that my runner has `ACTIONS_ID_TOKEN_REQUEST_URL` and `ACTIONS_ID_TOKEN_REQUEST_TOKEN` envs set, and that there seems to be connectivity from the runner to the URL specified in the env
```
sh-4.4$ curl -v https://pipelinesghubeus13.actions.githubusercontent.com/HF......
....
< HTTP/1.1 401 Unauthorized
```
401 response code is expected as I am not using the token in the curl request. 

Any idea about what could be causing this issue? 

PS: Other actions that make use of GH ID token work as expected. In the same workflow I am using `aws-actions/configure-aws-credentials` and that works perfectly fine. 

Thanks in advance!
