### ISSUE TITLE
allow to pass a list of docker images to attest

### ISSUE THREAD

**Issue by caarlos0** [actions/attest-build-provenance#454]
Hey!

So, I was thinking it would make things a lot easier if we could do this:

```yaml
      - uses: actions/attest-build-provenance@v2
        id: attest
        with:
          subject-images: |
             registry/image:tag@digest
             registry/image2:tag@digest
             another-registry/image2:tag@digest
          push-to-registry: true
```

The list could then be built on-the-fly if you're using, for example, GoReleaser:

```yaml
      - run: |
          jq -r '.[] | select(.type | startswith("Published Docker")) | .name + "@" + .extra.Digest' ./dist/artifacts.json >./dist/docker-images
          echo "IMAGES=$(cat ./dist/docker-images)" >> $GITHUB_OUTPUT
      - uses: actions/attest-build-provenance@v2
        id: attest
        with:
          subject-images: |
            ${{ IMAGES }}
          push-to-registry: true
```

I think this would make an awesome addition, and would make attestation as lot easier as well.

---

For disclosure: I'm the author of GoReleaser.
