### ISSUE TITLE
feat: allow passing multiple container images

### ISSUE THREAD

**Issue by shyim** [actions/attest-build-provenance#56]
Hey,

I am building a docker image with a lot of tags with `docker/build-push-action@v5`, It would be nice if I could pipe the same list to this action to add the build-provenance to all tags at once.

Kinda like this:

```
      - id: push
        uses: docker/build-push-action@v5
        with:
          tags: |
            ${{ matrix.caddy-tags }}
          //....

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: |
            ${{ matrix.caddy-tags }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
```
