### ISSUE TITLE
feat: add support to passing multiple glob patterns in `subject-path:`

### ISSUE THREAD

**Issue by kbdharun** [actions/attest-build-provenance#57]
Thanks for the new action (I have been playing around with it since this morning with my repositories), I noticed the action fails when passing multiple glob objects i.e. `subject-path: 'language_archives/**/*.zip, scripts/pdf/**/*.pdf'` (or) `'language_archives/**/*.zip', 'scripts/pdf/**/*.pdf'`. 

Allowing this syntax would allow attesting only specific file types from the build process and would also prevent redundant usage like:

```yml
    - name: Attest generated Zip files
      if: env.zip_exists == 'true'
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: 'language_archives/**/*.zip'

    - name: Attest generated PDF files
      if: env.pdf_exists == 'true'
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: 'scripts/pdf/**/*.pdf'
```

For full workflow reference, feel free to check out this [permalink](https://github.com/kbdkorg/tldr/blob/55f1f3af2fc915dc5df48b5a79a57a576ef26308/.github/workflows/ci.yml). I am evaluating the action to eventually propose adding it to [tldr-pages](https://github.com/tldr-pages/tldr) where I am one of the maintainers.
