### ISSUE TITLE
OCIError: Error uploading artifact to container registry with Google Artifact Registry

### ISSUE THREAD

**Issue by lodig-einride** [actions/attest-build-provenance#606]
Hey,

I am trying to use `actions/attest-build-provenance` to attest an image that is being uploaded to GAR.

I copied the [demo action](https://github.com/bdehamer/attest-demo/blob/main/.github/workflows/oci-google.yml) created by @bdehamer as much as possible, but `actions/attest-build-provenance` is failing with an error message that is hard to understand for me:

```
Error: OCIError: Error uploading artifact to container registry
FetchError: request to https://europe-west1-docker.pkg.dev/v2/[redacted]/security-gh-attestations/blobs/uploads/ failed, reason: Parse Error: Header overflow
```

![Image](https://github.com/user-attachments/assets/65ba8d74-51f2-4adb-80a0-a3b8b43e93d7)

My action:
```yml
permissions:
  id-token: write
  contents: write
  attestations: write

env:
  REGISTRY: europe-west1-docker.pkg.dev
  IMAGE_NAME: e-security-experiments/docker/${{ github.repository }}
  GCP_PROJECT_ID: e-security-experiments
  GCP_WIP: [redacted]

name: Build and attest image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: GCP Auth
        id: gcp_auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ env.GCP_WIP }}

      # We cannot use gcloud auth configure-docker because it is not supported by actions/attest-build-provenance
      - name: Login to Google Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.gcp_auth.outputs.auth_token }}

      - name: Build binary
        run: go build -v -o main main.go

      - name: Build and push Docker image
        id: docker_build_push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.docker_build_push.outputs.digest }}
          push-to-registry: true

      - name: Fetch artifact index
        run: |
          oras discover --format json ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest | jq
```

I think it fails in `@sigstore/oci`: in the `Registry.uploadBlob` function called here https://github.com/sigstore/sigstore-js/blob/main/packages/oci/src/image.ts#L78, but I could not debug it further.

Thank you!

**Comment by drGrove** [comment]
Seeing the same issue pushing to ECR

**Comment by jkylekelly** [comment]
hey @lodig-einride & @drGrove, thank you for reporting this issue, and for your patience. We've attempted to do some initial debugging but our attempts to push to both GAR & ECR have been successful. We may need to further investigate what headers are included in the registry's response and how different configurations may affect them. 

Sorry we don't have better news (yet), but we'll update here if/when we determine the root cause. If you come across more details, please let us know!

**Comment by lodig-einride** [comment]
Hi @jkylekelly, thank you for your answer. Please let me know if I can assist in the debugging by e.g. running a modified version of the action to enable more debug logging.

**Comment by eliheady** [comment]
I am seeing this while trying to push to ghcr.io and I'm also happy to provide debugging or other information if that would be helpful.

I don't have a previously working configuration, this is seen with version 2.3.0.

**Comment by mbianchidev** [comment]
Hi @lodig-einride it would be great if you could attach the headers of a failed request as @jkylekelly suggested!
In this way we can verify it this is a failure tied to us or something about the target registry in a particular edge case/scenario.

Thanks!

**Comment by lodig-einride** [comment]
@mbianchidev 

## Debug methodology (putting this here in case you disagree with the methodology):
1. Fork attest-build-provenance and attest
2. Change [attest-build-provenance to use my fork](https://github.com/lodig-einride/attest-build-provenance/commit/9a91ef19dd1426cffdef9e8bcf8ac08b8b9048ca)
3. Change attest to [add debug logging directly in the action's code bundle](https://github.com/actions/attest/compare/main...lodig-einride:attest:main)
4. Change my own repo's code to use my forked version of attest-build-provenance (which uses my forked version of attest, step 2)
5. Run the CI

## Debug results
This successfully started my forked action. The log works, and output the following, more detailed error:

![Image](https://github.com/user-attachments/assets/f0df8fb2-b861-44af-9009-2cd6440d10dd)

The whole error is attached as a file: [error.json](https://github.com/user-attachments/files/20793596/error.json). The buffer has been translated to a regular string with the following code:
```js
const err = require('./error.json')

const packet = Buffer.from(err.rawPacket.data)
console.log(packet.toString());
```

and yields the following string:
```
VQjPGGl5yasd2UfA72phgCwF6Wnbf8uJd25b_m7u5K1Nc86bmdtHdDzxA_qnt_e7FFSu04-R4_dTILNE_6mC8Bqr_UhQ2kPjOAXOOLQWwZSzxie_c_T7K3ZiTLMuU1T2G7fN5CQJ_evRLP6n1UYv9FS_8S8yB3q336DVXGG0bFdaC0sUxrbDOoWZ_XXsFlbp3hp43-UfTQuGNe83MS60sXl12qjRLo5zFQd03cQ8A6rt3CuzNjJ4wscCss17bCunfdBmBgu98H7jS8gTTZwxLVWlK-TiNoK39jq7ASsMNe_dLDVA5Uez17G9Ld8V_gC7YdMKRPL_eUUSCewecGc8O5g8iUW7V639GB-3V5rigUv9o8rM5ODi3_HRDPffkDTT41OGPeSSswiNVcAdnmC0yhrvHsUTSfMLMTc8HOOZuZq3Eki1miIosLIzbvbyq0vJlS8XoInicKNDFsvhFupF8DfKOeIDd3ztAgrpbr-2jPHMzVFt7Qdks5mkpTr267FCUOi1hvInqtszRNbFa58Qpi4653FIxwSS1a4S6zvZh2FsH3YBvct8CNRskoZ84kNWvZajnwAlSogtopB1f8w1Mrsp3xXFu5bMuzd3UQB3o5SHfYypUP82jBLpjE8rqSOrd7AwiDD_6BY_G2RoZWIwel-WdnO_ULIUP0tmF0RKjC_Cx9P7VZnmajdLuR1Ig5ZLsWYwryzTupokQhQeAR1wkPMoALHxObm2nYClO3ZGcoRIxI4LaRnol0e2t9x25KxtPa2TRJI3q8LONZyTgX2icBgtcsKrO71Obu9IdJ1_MuhX841llBbpF606UkPmybF29Y7--lQExEwf5rxNClez6dFbYZwGrvCBz78NJ9agk7ogLZBrrHJMx11t89wqai4ZDfhUsQoQUkwU9GezRKAamjE5QANQQdWrbGoLiP9D5bFbWMLV9MeCNNgktaZpa4evxMxGYfOJBo8FUfdqe35SoXWh4LdwcM1CtzbRRVp35J7NMamWz5Cy_oyo53f2z3qTfMZonoYbDnPqtZc0p528xnMUw58zUC8cqe7pbYVP-I_zylu80TbORZ8XYefzEkYvtIfU4R9XTAv7WDvOPQbEPAYKFEmyakeWajnZhf854sqq7PUAx6CBUjw_FgwpeS2tvx6vocN3Bw1x5unemW0m0Jew5S4oV3XQPVkZUbVmK9W0_M6r7QsuFg2ltTt3wRtExgXWWNQlOcqvOZd1wLFgkO_Yhxg-VWqxGKB356jL-sgHIhNP4rTABcBbtRsmV1hnFYDcL_20O2_H7Bv9kM-H2QnZrYJDr-fB-lx2UNcWzF8yjOAk42NXMVg6OZeWrjNAYA9MvNuD-rZlm6Fa4QccSdt7k8CiGV7DUVIy7tqOtez0OAyBw94F9HTYIXI92tnoPZEVb4xhMrzgI3E9KIwPhTYwijnonf4SNdQuNRPCTQvTXJr2fHPgSXEOnLoUa9GwcAVU8JOtXLN16xOcG2gl7lhwq7-6-c4n6T4VOHvJDeLGZ9WQ16Lcq_YpGq6BeVPLsy-g8lOA5-5UnN4_TW8kqAU9LLPVonc15Z3N-FV2nMay_Vq48-eKm7w8JxTU8xv00fjdo9ydUN1ln3BJqHncnQ_H1athDDajUl0DUzLTdXplu3fJuX0sxSRnvbsE38RZTvxl-RkbPkFdUwC-BBbYbj_TTi_pjD2bUCl4pQYbGPZeXHo7qAOtzvYBDSHJr1A7vJxJA_-x3oey7gG0K7VjAsDpmL6X3-i3nqmYDerFtWEwuIBi2Fe9FTxc7xMm4ab_W2xaRNbKyHhNbG2Tvx7Mne4fkDFGKS0QZ6N7rKYUgXzUgK7VWjs83RSB7BvuZsMUzIiymE-kUhuNSem_n_LaxURiF9BNj20axNuFaeS4kx90RGnM8TmFEn8BSFUeQJkGwGKeZvSeCyN670Wqxmixy4HZTGFH7q7_tZl0rih44NK2xxDTGGWrKER-rkYhEMhRduL3GpJb0z6lWmZnaPD_acxqtqi7ApelOCTtPEy92BByFBoUjwbwKsgaA2wPrSYj4cknMeq3pmiL_5VcPQ472ac6XcL55Qpe1ZLf8Zc-GpXV0CxzH9WF2p-7OnJ5ejoHmamYQ3kNfW5x3xBPbIopAn8vpMYMXC0OJhfYEf_CyzZxSMcnZ1ea1A-oWaUgE78vNQf2dvK4cDhF-SwY5wVWKhESPt85RwCpMMc7bu88Y0zmUKMPfpzY92OxZbrw7ubRXibWe_9FEvnX-RWwlPsh67Q-C_p_kdK4uKHCwXkmt5xLNza4XWfeMseyKwCq-yqP6Yygof5RhkQhkikqHmz973EmZDDkg_rpm90PK6H6M4rs9DoYEyJP70lZDjQDyG8yaREQl_FI9EJegTC0gJ5Kn4OE0b1bLSxl4R8zBhWaw80wiCwOaJUU-9BKSpL0RDXqvmrUMoE3l8TZiGWHwJP9Dn0PusPIlhO2UWycEwXrXFrlpFLewGidTgQCZfQApFPO54s9QTcmdN1XelJ6iKQ7axAhbJAv1hje1DIn_HC9PTxezRYFFSawaCzGdfDam6_9UK3nHK3HeZjuH_1ZRWb2CSYJ4OTQDCTvJ-ptN8aN_eKAvn2uxVIjFDNuHx-YEaQnhTcoCnGn4uXXfF0PRUm28SdBR3Yrqm6tKIbaoO1Zkf2NX5dXq7AFLW2FqoMirwYxpOzhEc45Ju3eq4SjylvutY6qC08pXT_K-QUwX00Dn6qZsDXDKL_Fq6noei9SUgd1j_8UGv90x0dqyki_C0P7L_9DZq-PQKbI8AX7tvlnOcPxGm29-xnMK2T6azAi-8xTqmEeMV95dwIWbfSDjidQAMac16cuZDCTwZO2kvGbEePY2TEHmLZaJV4kTalSNG0y82vS_3Pb5DzkcDo16_IAprcK9zGCiCFNPit5vtfUT1yDTRL0GdM3cD0a1PLBmHGyPbd8GD9kyVwUnSMG-Vh5oOfYRtcO5q6xuJNgg_sFfO-oLOzxcvHgdWwbKtET8ixWkTNEVaukPhXBKldOsTgOZtfWTluCc5C5oTbhSf2rpbVTbRcnmj2KiPgH_fGqp9JhTWRI39FLJysqUu7TrKZID78uYjLB9HBh1MpSM_mJr6l0ffico3jk8MVZ2aivXzCt6H01y13l6-nU6uVxHhSicyyZTRYwXZTYAtH4h18vrvzw4S2vJhB637NFv4WE-9_2PN3Nb9iZBz68WUf9U2kXhY_cVHpFnxuFzObXj_FxQuNKCWIYWA6j2EmYN9hQWejdDp9IqRwZvlF0Qt97NlFbwc3E0eg-I62eHduLU3mOJzJSCzYOlOB71NMGKOSuh8l99NjEveDIAz1YFqTeUUNdzd1hdS6vZ0pdkYTOc9LioePfJOwrc7_UdkdQ8l-XcwZCXwQm0xdwby6-XRzMhHLkfsBhPoePJrkDDGVUqtdnxx16NHa9stvFSJ7AExT2pU_CDAQ6_x5tNpNaPr3SMkaL4tHNeFcNAuFLE-fO9aSTqKe_HfwOcC9wzbBxo8Xx-VC7mHFK18FSIb7XfsL-PYKgBJWp8tTg2sBzBnyEtlS3SKKCoi89AMj7vlUPVhxTPeAlZHMdf3VDy3k4ArRF78NM7y1LcGpqNOFvu9DIe8VpkS5X5VNOrGC90yn6Y00GAzWGHP-_Fo3b1pR8aFJ2yooOid_Csa5KOrHQzerOZdiXoAWv_ppRoH0OAxlw2-XVMcxeYmerYGPnpOnR8nx6F-ckc8G8XMW-iRsqyHwQ6QiX-DyMbTvr8uAMtqgUt3hHEmfTU2_UanCvqKVAJL35Z4bqvR9dOmB2X3j9YJGNyohNW2YwMHXGf7u9Pwbi-6NoWrpviuZJr3GPhpiNrgFoilGb1AYDZ46GH2B-IIZ-ljnyoCw5NBgGX8caue4cxuGN0YbZysvt268MT_KzC5F1ZSpGMvMTH6WKoe9JX_GoLmM7zoxrF4Lxb_hRF__zDIQgstUov_aDDMxjGd4_K-wKzivTu8dRpzjP55-_D0DaBcznHmkoBzNMenfUeDttqffXu79Ia_quunAEmwmNViBZ6qYQuPgDPhHTAqfD5AWL0LN3X-2Om2flIeNFqh0gZxZyDOZ9RM2_W-SHpYGFes4rv45VDyUKClzs9fhfzqAjlbkqczSiGfHUEdpyhBGrYGm_KeMoLy_Fvl2EqrBMQnYiW7z6Zm7wmU7UQw3QycFtqjQNWkzF-77H7Y9KdIMVZs-o4mn-pQjKoRtvsBtU6oZrUTpuuSHkkwse5XDCe_GLFvyMit-VgixP9EHKKWeTXUnFnYF5I8GvTqBbaUgoq--AcuHPvmETLd7ufshcUMEBsIcJI8NEO0j0eADRfJgE_wVr0hPHGGCdCh43dt-SruT-9rxnOANR8O0EYsLneeIPnUnlQKE9T9pjYrP4uGo7gaE-MPcxkroBvKQ4z5-ML2PVP8S21ewBAbV6g76kZ0AhJ4mLMYO1ovAACgx_5vARxEwXv2LI2gXzVAaaD7lU38YetpbmgwH6wuT6mqpfoQCDf7ukOiLbiLsMqnKc6FjqkmwVj6gpFDpX6ffEet2VH54jtH2RQRkupd_1E96mGVlDt1iKCmE1_MvH1gnP1I2BTg0InGttHucIEAqc7kzRBqzdKM7ddx6jEDixN4JRC51Sda48-lRuQHKI184IgWqdPqellKNvuDetqJpA9hYcoDNMvYGwWtDSkzwtu5TfgilngUqVKusRXCfapKcc_FhgtDACr8er3QqIXQZtjOu42SgL_L9Rj8mS8-mgULQmhZGarVdJ5tQ4M5e7Hg7r1Z0OO_4XhzSU7Ni1KV6P0PTOeUg4yvWVsRI-GUnJYErlbJHeQAdWMwGN6HDZaRVMfvFF90W77zFDxup37XCSpxne2_mBYC7aufTSim_nq-v7zlUk28r4iZqb9uuKWax7HSteEYEGA65bu4ArPf8W0FizUnMXoWiaWib2Qe2OGyj5aX17ARFWiZukfoHi0cWrTHO9hptMPnJu6sYtMeQ72DHh5khXht_tRs3jv5n6Ak1yYClSz3rkAc7cWGC05YBdXo_SPZoi9LCm1nYfLoitGgCCsmMa4miEKmKnIpMzSMvEOMQgAD5EzaxzvSMwbeyMSCoROlihEaZ9Y8sHFTxmblJwIhjHPkSJs1_vOTZWv512LHUt3TxJ9fYNQ9wZZtmhH6KlkYplX0oYoQunCRctkrIUuHCB59N2Y7ugBa5aShgNcAlCQLw6FSIsppyBpLR2nDHZUE6qGl-b8RF2bF0_1AST3DPDfW2is17LZSh2D4L-iDRb8SFQhhzIox8TdBM0_dHYVlm09c7lcfAGaQW-wenyYN0QDwSdHS_yRMIExlSMp4YMi5VrpI_YBqHLWB12A7K6CtX3TSOo8mN3gBrFCl5nP0GRnwq37BN_2ymRQHjq1XG5hG-PIYqYaS5GEyI9AzQm6FlcVMubY1oQpyNf4W5fuQ4WiEa0tQF5q_lPKLh1JJh9NpVcgcUwbTVcaEw6PdpItA8WQ1Q0vfukHN8Ejuh6m4Im5UXB1F0Dd9_6IEqI_iYcw_hlqheVR8I_NkT5vOCtIEobUeWAnyXlpn05eLVx78m723B5jQ_uPJYxyuHWghbj4hYanvUIT4PiPebaagPSStOqYMl37UGhWzryyCemksOJ_dy-PB1OMWZWvKC1xCaXDjadOpv5WWsZSuSvphdDqR8LTiwWHp6Bp9zSETwAu0D854YYohwCa_S_33Cuf7y2v-xiRfkGF9-5HpYSQ4aAaAVAViWM7AzMGboChePxoVpfrS39bFuNmJHZcgi3eUmjMeyIPXLh2OjUaF6mkGpSdjipyWW34oAXuZmiphKn2f8cvSQcqRAm0sRfA8iMY8DJWtta3ZAyljtVaAqXt980zZj9PqFYzcxpw-fO9u7gThBQZrgMd2VtV7voQOwzoW_9GW6ZCno8pJhKvXn3B9wfJaiEkBM21DOB1_g0a01Hx_D24kf8OZ3kKePyUbZhx-slVSpSLd1lJZNGRtqQIp5OA2S4KuebIPbNZ6MCDKbzRDXtHM-9PPSm-na2Pxx4y7muckuRa6ZJkOKHTFqvS3DdPKomjQtkRY5HdmY2LMvlECU40HOtf3J3ao1pdBHy-GJEj_-1kVAkIkrPJTrm9rJiNJ4tNYEC6dWyvQGZNsDPse2FI-pt5GHmftHPDZXPLgVFV0NkxdYJ8kbAYsBDhSYeztDzGxM6y-1LKuD0VO3PisEImIlwWVu2tFi1s8pbJniIVXb4XNfOVFp-zTSVUNaB_bp7m_ZS_HOs164JLLctLSGf5XR_I6tB-NkJgxLqhgjQ5-ANjd2bLK4Fko1J0ab-4XNcLOt7BRXNRlcxPU02h3NS2MiJX4xkT1PutWTnjSSs-I3JS83Ze9J0VZdyPipCv-grxzW4T3lObZtJ0sQfqvV-yFw5llo8tkWylLsfc7BZ6eQHCgVlmxVKLcM1DbA_Eu-GxUFz9INlA_1HvypXFE9tX5wl9dSrMEb0E2Vg9UBHpJDeFCOKsf-knbdJZfoBpjve4Lasxb9jDbzw0LNWZ83VmadMdugiXIwpo5B2mMutnbr79F7COzQuYrET_RFGhPWSiQ4eJg4ArGq91viBunoWBsQEjPVQD0yu6mHE1kkQOwTyJuG89_cstNN501yKRDXe-SE-MC07XypJqqvoEj17BpJm1OdD_6lrIFzV9fZLJnapU2m2_LWLe-9UDyozR2wIhXwzd9j4TVCFJb4rUBCLOoF_K4W7_dr3kEfnd-Gu9LOX65WRgC4rSivGu8POjJb2KC53FsZ6U1tIC7u04rj8kW64K3lbHzUW6yuAwb5qBF3jra0eCrbv6IdUYd2rDkAm8RToz5HEiabn2H0DEdY-FBwEdDR2wOEV8kH7mjmJFVgndCCXsnKEeq1WpHj7XL5yqz5toqguU2-HJ7aTX9vPdl5iK4Cwm8bVKMVVNI2mZiwow3Xs6fdGHh7iyr91mlwdLUrWYSABSM44y-3gfUd-c6s0Vxxgm7F_-2eiw2ZNKZkCgTEbFi95ZsWwYiLJL8q63fHU8hEKWmxL5I4Id1Lq4BAGkpdsV3QB7SCptJOhVJu22qoxl1l7BOerDnsq9_zVA3R-8fG_gL50_T4kUyQiKyffNy3ed9ETHSCoD1W05f37YTpbS3G2SMY3kaTOMnc7gea0UvvvgEad1bbEqecEKcry0lIOT93YMOe2HHnH24WTVOdj9qXf9YS9muU8kR2O-0G4TlKhV3TOONcvDfZMcsGhinbm7yLTYV6yzkKVCBZOK_Hd83KEUfI56VXFdoFlFFtZfoJMX5zigmboU9Kdo-Z8O3dtkqbjHwo7Ag1N40-ZxDf9lcdDS1J-WSB8n-H-P2SV2XlYtTfGSZBrn-RDkAfcrwGAsKFQirYcIOEAgvvfR9iJZdB1QCjtR1CsqkvVedR00b4gILJjESSnqmPX9XwxLXq047YnUgcoprlvJ9P_Eka7DZZuj4sAbw2dqqWlSReDAuo0wFX5CFZiy6nH7-iqDAKh_RVh42TtmABMna44fU7w6-kM5YaVSXOYd3TuiX2jhDPsIrCUzG8SHkel2gBscyD6pSianywS0UcWlwItydxTIQ1lSdl_DTs0qffDfcS0c_w_TZm-bHmXp4j3geQIu9GGvldvzcrggSztGGL2nGvAEi-9Fb9elTj9KixGdW5Ms-bCRHigQXzlyAW383-XG-klwEx-Gj9_Nb3DC-2BUwRDLgY-rONwvmWmxvsWQXtbHBS3-QE41IygdiegRkLXvdpQT2Ff5N0sYToLQds0IZL7nZb7flZpXMd7SH7zL-GZ06JArWq8CajPA93G44Y8hpARZjgrRIFtsejzvAZcJhTgA2-iFrp7RIB3bV9PiIh9WuSkVA3u72q4IqqmhSdZuvdWXoQEx_XUkyYK2cTl5BHRHZ9WbxFf3dZzdG0KahBySmS0Ex_mQNdoyTb0dcj8JfX-f3zLzY5pkrvQZPbUDZg4DsssN079lMoGrrXlf89mwIZc77_KwgSPuFz8sa2QAAGPgdOElnL8cTjmFW35hnkEkZI8JFMdc3lKUHezh-QUFJyQfiLT7m4-5KSkV_31uCiKgGQmT_iyfMbjZrUQWrCh3b8IysmRLZUHkyozFnzWq2wSd600gNb6y22N24PoBW8QjOwNmJkoU1V1-UK8UTqmPcFDjKaC_H_REe02dSPRW2yRdbptiyCy3Q34sQ5LUK8WrOAudH1nJMSPgAZvoCNbI4LRulkpvgx7koi3fDJH2SvaK5bTf00N5idjOoq6kaWifyZUspsymM8EezS4hQo0J1ZpcvNY9yBGLm2CRJ0yIWGXvGeSIiA0aBMp4hod1qadAkznrzPK_FGr7xV3sfFSV4DLFbWiEyk3QDibbVtTwGuWpQs11cNVaJHql8b0qxJioW9nlzsqxb9BP7IMORFUQ0ALmr9vcWdaQ1ZYSbwBWJRxpjciZ1f7DQbdbujiUAs5pnc9ocYVnXdaGm6vZ_WVkxy4aSy3KjwRwHQmYUW-IvC0PLwz1NnEW-Xal2fn3BbkgHcOmYlmP1K3Ar8XVn8yzxQDlYiohGqyJCc2Lrkm9f17zh2AyXGktRV1e2vEEJLWVZUzDvz6l1qzE7cGStSOWUvCJ5qsLYVRHnhtf-l3lOxOeNRk50njvS37Wt3UNaI5znjNN9_KwVrRFtpwXJOgQdTxL8lqbJH6a_Bf_7_oO0Qtjo=
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0
Date: Wed, 18 Jun 2025 09:47:59 GMT
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

The first line is clearly not an HTTP Header. It seems to be base64 encoded something - but I am not quite able to identify what.

I hope this helps, let me know if I can assist further!

**Comment by mbianchidev** [comment]
@jkylekelly the above should be enough to reproduce/test 👀

**Comment by jkylekelly** [comment]
Unfortunately, we've yet to find the time to determine the root cause. We did attempt to reproduce the error, but were unable to. We also used the forked version of attest to review the debug output in our workflow. The upload succeeded without error, and returned the expected headers. 

The distinctions between your workflow and ours are:
- europe-west1-docker.pkg.dev vs us-west1-docker.pkg.dev
- slightly different auth for Google, example below:

```
      - uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          workload_identity_provider: ${{ vars.GCLOUD_WIF_PROVIDER }}
          service_account: ${{ vars.GCLOUD_SERVICE_ACCOUNT }}
          token_format: access_token
```

Perhaps this helps, but if not, we'll update here if new details are uncovered.

**Comment by lodig-einride** [comment]
@jkylekelly @mbianchidev any progress on this? FYI #666 seems to be a very similar problem. Thanks

**Comment by jkylekelly** [comment]
Hi @lodig-einride, we appreciate your patience on this. I spent some time today setting up a Google Artifact Registry and have replicated the error reported in https://github.com/actions/attest-build-provenance/issues/666. 

However, I'm unable to replicate the error you initially reported. In fact, I'm not even able to push an image using an almost identical workflow to yours. Battled 403s for a significant amount of time today despite being fairly confident the service account permissions and workload federation are properly configured 😓. 

No solution yet, but will update here if any progress is made.

**Comment by jkylekelly** [comment]
@lodig-einride, I should have enough familiarity with Google Artifact Registry to better assist now. Can you share more about your GCP setup? I assume you've created a workload identity federation. Have you then created a service account and granted it the appropriate permissions?

If so, I noticed in your workflow that you're using an `auth_token` instead of an `access_token`, which means you're not producing an OAUTH token as is expected by the `docker/login-action` action. [Example from docker/login-action documentation](https://github.com/docker/login-action?tab=readme-ov-file#workload-identity-federation)

**Comment by lodig-einride** [comment]
Hi @jkylekelly 

Actually, the `docker/login-action` supports [Direct Workload Identity Federation](https://github.com/google-github-actions/auth/tree/v2/?tab=readme-ov-file#direct-wif), although not directly written in the README.

Indeed, Direct WIF is the example method provided by Github themselves: https://github.com/actions/starter-workflows/blob/main/deployments/google-cloudrun-docker.yml#L55-L73

Furthermore, as you can see in the logs of the GH action provided above:
1. The login step succeeds
2. A "test" file is successfully pulled from GAR (confirming the login step succeeded)
3. The Docker image is successfully pushed to GAR (confirming the login step succeeded)

The authentication method you are describing that uses a Service Account is different ([Workload Identity Federation through a Service Account](https://github.com/google-github-actions/auth/tree/v2/?tab=readme-ov-file#workload-identity-federation-through-a-service-account)), and also not the preferred method. **I would like to avoid using this method (WIF through a SA) if possible.**

---

With that said, I have tried creating a new SA for this purpose and used WIF through a SA, and the attestations gets created (see below for working example).

It seems like the root cause of this issue thus stems from the authentication method used, and that the `attest-build-provenance` action does not support Direct WIF. This should preferably be fixed by Github since Direct WIF is the preferred authentication method for workloads, or at least documented somewhere in the `attest-build-provenance` documentation. 

Thank you

---

Working example of WIF through a SA
```yml
      - name: GCP Auth
        id: gcp_auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ env.GCP_WIP }}
          token_format: access_token
          service_account: ${{ env.GCP_ATTESTATIONS_SA }}

      - name: Login to Google Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.gcp_auth.outputs.access_token }}

```
