### ISSUE TITLE
TypeError: Error uploading artifact to Google Artifact Registry

### ISSUE THREAD

**Issue by farzanhaq** [actions/attest-build-provenance#666]
I am encountering the following error when trying to push an attestation using `actions/attest-build-provenance` to Google Artifact Registry:
`Error: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined`.

I am providing the subject name, subject digest and have push to registry set to enabled.

My first thought is that the bundle here is evaluating to nil:
https://github.com/actions/attest/blob/main/src/attest.ts#L40

Any tips or suggestions on how to overcome this would be much appreciated!

**Comment by jkylekelly** [comment]
Hi @farzanhaq, may you share more details about your failing workflow? I've recently replicated this error while experimenting.

Are you by chance using `gcloud auth configure-docker {location}`? Here's an example of a workflow that runs without error (note the use of `token_format: access_token`):

```
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: [redacted]
          service_account: [redacted]
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push Docker image
        id: docker_build_push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: [redacted]

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: [redacted]
          subject-digest: ${{ steps.docker_build_push.outputs.digest }}
          push-to-registry: true
```

**Comment by Clockwork-Muse** [comment]
I'm hitting this too.  It seems to be intermittent - I have multiple successful runs interspersed with failed runs.

The relevant portion of my workflow file is:
```yaml
      - id: auth
        name: Auth to GCP for GAR service account
        uses : google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GAR_WORKLOAD_IDENTITY_SA_EMAIL }}
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ARTIFACT_REGISTRY}}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - id: publish
        name: Build and push container
        run: |
          dotnet publish ${{ env.PROJECT_LOCATION }} \
            -p:PublishProfile=DefaultContainer \
            -p:ContainerRegistry="${{ needs.check-release.outputs.is_release == 'true' && env.ARTIFACT_REGISTRY || '' }}" \
            -p:Version=${{ needs.determine-version.outputs.version }} \
            --configuration Release
      - id: attest
        if: steps.publish.outputs.container-image != '' && steps.publish.outputs.container-digest != ''
        name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ steps.publish.outputs.container-image }}
          subject-digest: ${{ steps.publish.outputs.container-digest }}
          push-to-registry: true
```
[attest.log](https://github.com/user-attachments/files/21946269/attest.log)

The login _and push_ of the dotnet container image works fine - I have the output logs and published container images to prove it.  The time between auth and attest attempt is less than 30 seconds, so won't be from token expiration.
