### ISSUE TITLE
Error uploading artifact to container registry when using Google Artifact Registry

### ISSUE THREAD

**Issue by capri-xiyue** [actions/attest-build-provenance#73]
Does `actions/attest-build-provenance@v1` support Google Artifact Registry?

The build-push step successfully pushed image to Google Artifact Registry with this workflow. It's failing at the attestation step with "Error uploading artifact to container registry."

Here's my job step.

```
jobs:
  build-push:
    steps:
   ..........
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: '${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}' // example is `us-central1-docker.pkg.dev/repoA/imageA`
          subject-digest: '${{ steps.push.outputs.digest }}'
          push-to-registry: true
```
Thank you for your help!
