### ISSUE TITLE
Support creating an attestation for multiple files

### ISSUE THREAD

**Issue by josegonzalez** [actions/attest-build-provenance#78]
If I understand correctly, we need to attest each file one by one. This is a bit annoying if your workflow builds artifacts for several architectures/operating systems. It would be great to be able to specify multiple files at once.

**Comment by bdehamer** [comment]
The `subject-path` input allows you to specify multiple values (with globbing support as well):

```yaml
- uses: actions/attest-build-provenance@v1
  with:
    subject-path: |
      /foo/*.zip
      /bar/*.tar.gz
```
